apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: baseline-api
  name: baseline-api
spec:
  type: NodePort
  ports:
  - name: "8081"
    port: 8080
    nodePort: 30081
  selector:
    io.kompose.service: baseline-api
status:
  loadBalancer: {}
