kubectl apply -f redis-pvc.yaml
kubectl apply -f redis-deployment.yaml
kubectl apply -f redis-service.yaml
kubectl apply -f postgres-pvc.yaml
kubectl apply -f postgres-deployment.yaml
kubectl apply -f postgres-service.yaml
kubectl apply -f nats-config-configmap.yaml
kubectl apply -f nats-deployment.yaml
kubectl apply -f nats-service.yaml
kubectl apply -f api-deployment.yaml
kubectl apply -f api-service.yaml
kubectl apply -f consumer-deployment.yaml
kubectl apply -f vault-db-persistentvolumeclaim.yaml
kubectl apply -f vault-deployment.yaml
kubectl apply -f vault-service.yaml