apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --controller=deployment -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vault
  name: vault
spec:
  type: NodePort
  ports:
  - name: "8082"
    port: 8080
    nodePort: 30082
  selector:
    io.kompose.service: vault
status:
  loadBalancer: {}
